import { CanvasElement, CanvasBackground, OGTemplate, OG_WIDTH, OG_HEIGHT } from "@/types/editor";

export const templatePresets: OGTemplate[] = [
  {
    id: "blog-minimal",
    name: "Blog - Minimal",
    width: OG_WIDTH,
    height: OG_HEIGHT,
    background: {
      type: "gradient",
      gradientFrom: "#0f0c29",
      gradientTo: "#302b63",
      gradientDirection: "to bottom right",
    },
    elements: [
      {
        id: "t1-title",
        type: "text",
        position: { x: 80, y: 180 },
        size: { width: 1040, height: 120 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        content: "Your Blog Post Title Here",
        fontSize: 64,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.2,
      },
      {
        id: "t1-author",
        type: "text",
        position: { x: 80, y: 340 },
        size: { width: 500, height: 40 },
        rotation: 0,
        opacity: 0.7,
        zIndex: 2,
        content: "by Author Name",
        fontSize: 24,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.4,
      },
      {
        id: "t1-line",
        type: "shape",
        position: { x: 80, y: 160 },
        size: { width: 60, height: 4 },
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        shape: "rectangle",
        backgroundColor: "#667eea",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 2,
      },
      {
        id: "t1-site",
        type: "text",
        position: { x: 80, y: 540 },
        size: { width: 400, height: 30 },
        rotation: 0,
        opacity: 0.5,
        zIndex: 2,
        content: "yourblog.com",
        fontSize: 18,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.4,
      },
    ],
  },
  {
    id: "product-launch",
    name: "Product Launch",
    width: OG_WIDTH,
    height: OG_HEIGHT,
    background: {
      type: "gradient",
      gradientFrom: "#667eea",
      gradientTo: "#764ba2",
      gradientDirection: "to bottom right",
    },
    elements: [
      {
        id: "t2-badge",
        type: "shape",
        position: { x: 80, y: 80 },
        size: { width: 140, height: 36 },
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        shape: "rounded-rect",
        backgroundColor: "rgba(255,255,255,0.2)",
        borderColor: "rgba(255,255,255,0.3)",
        borderWidth: 1,
        borderRadius: 18,
      },
      {
        id: "t2-badge-text",
        type: "text",
        position: { x: 90, y: 85 },
        size: { width: 120, height: 26 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        content: "NEW RELEASE",
        fontSize: 14,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.4,
      },
      {
        id: "t2-title",
        type: "text",
        position: { x: 80, y: 160 },
        size: { width: 700, height: 160 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        content: "Your Product Name",
        fontSize: 72,
        fontWeight: "extrabold",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.1,
      },
      {
        id: "t2-desc",
        type: "text",
        position: { x: 80, y: 360 },
        size: { width: 600, height: 60 },
        rotation: 0,
        opacity: 0.85,
        zIndex: 2,
        content: "The fastest way to build beautiful OG images",
        fontSize: 28,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.3,
      },
      {
        id: "t2-mockup",
        type: "shape",
        position: { x: 820, y: 100 },
        size: { width: 320, height: 430 },
        rotation: 0,
        opacity: 0.3,
        zIndex: 0,
        shape: "rounded-rect",
        backgroundColor: "rgba(255,255,255,0.15)",
        borderColor: "rgba(255,255,255,0.2)",
        borderWidth: 1,
        borderRadius: 16,
      },
    ],
  },
  {
    id: "social-announcement",
    name: "Social Announcement",
    width: OG_WIDTH,
    height: OG_HEIGHT,
    background: {
      type: "solid",
      color: "#0a0a0a",
    },
    elements: [
      {
        id: "t3-glow",
        type: "shape",
        position: { x: 300, y: 100 },
        size: { width: 600, height: 400 },
        rotation: 0,
        opacity: 0.15,
        zIndex: 0,
        shape: "circle",
        backgroundColor: "#3b82f6",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 300,
      },
      {
        id: "t3-emoji",
        type: "text",
        position: { x: 520, y: 120 },
        size: { width: 160, height: 100 },
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        content: "🚀",
        fontSize: 80,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1,
      },
      {
        id: "t3-title",
        type: "text",
        position: { x: 100, y: 240 },
        size: { width: 1000, height: 100 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        content: "Big Announcement",
        fontSize: 72,
        fontWeight: "extrabold",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.1,
      },
      {
        id: "t3-subtitle",
        type: "text",
        position: { x: 200, y: 370 },
        size: { width: 800, height: 50 },
        rotation: 0,
        opacity: 0.6,
        zIndex: 2,
        content: "Something amazing is coming. Stay tuned.",
        fontSize: 28,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.3,
      },
      {
        id: "t3-cta",
        type: "shape",
        position: { x: 460, y: 460 },
        size: { width: 280, height: 50 },
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        shape: "rounded-rect",
        backgroundColor: "#3b82f6",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 25,
      },
      {
        id: "t3-cta-text",
        type: "text",
        position: { x: 470, y: 470 },
        size: { width: 260, height: 30 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        content: "Learn More →",
        fontSize: 18,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.4,
      },
    ],
  },
  {
    id: "tutorial",
    name: "Tutorial / How-to",
    width: OG_WIDTH,
    height: OG_HEIGHT,
    background: {
      type: "gradient",
      gradientFrom: "#1e3a5f",
      gradientTo: "#0f1b2d",
      gradientDirection: "to bottom",
    },
    elements: [
      {
        id: "t4-tag",
        type: "shape",
        position: { x: 80, y: 80 },
        size: { width: 120, height: 32 },
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        shape: "rounded-rect",
        backgroundColor: "#f59e0b",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 6,
      },
      {
        id: "t4-tag-text",
        type: "text",
        position: { x: 90, y: 84 },
        size: { width: 100, height: 24 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        content: "TUTORIAL",
        fontSize: 14,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#000000",
        textAlign: "center",
        lineHeight: 1.4,
      },
      {
        id: "t4-title",
        type: "text",
        position: { x: 80, y: 160 },
        size: { width: 800, height: 160 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        content: "How to Build Something Amazing",
        fontSize: 56,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.2,
      },
      {
        id: "t4-desc",
        type: "text",
        position: { x: 80, y: 360 },
        size: { width: 700, height: 80 },
        rotation: 0,
        opacity: 0.7,
        zIndex: 2,
        content: "A step-by-step guide to mastering the craft",
        fontSize: 24,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "left",
        lineHeight: 1.4,
      },
      {
        id: "t4-code-block",
        type: "shape",
        position: { x: 900, y: 120 },
        size: { width: 250, height: 380 },
        rotation: 0,
        opacity: 0.2,
        zIndex: 0,
        shape: "rounded-rect",
        backgroundColor: "#ffffff",
        borderColor: "rgba(255,255,255,0.1)",
        borderWidth: 1,
        borderRadius: 12,
      },
    ],
  },
  {
    id: "clean-dark",
    name: "Clean Dark",
    width: OG_WIDTH,
    height: OG_HEIGHT,
    background: {
      type: "solid",
      color: "#18181b",
    },
    elements: [
      {
        id: "t5-border-top",
        type: "shape",
        position: { x: 0, y: 0 },
        size: { width: 1200, height: 4 },
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        shape: "rectangle",
        backgroundColor: "#3b82f6",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 0,
      },
      {
        id: "t5-title",
        type: "text",
        position: { x: 100, y: 200 },
        size: { width: 1000, height: 120 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        content: "Clean & Simple",
        fontSize: 80,
        fontWeight: "extrabold",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.1,
      },
      {
        id: "t5-subtitle",
        type: "text",
        position: { x: 200, y: 350 },
        size: { width: 800, height: 50 },
        rotation: 0,
        opacity: 0.5,
        zIndex: 2,
        content: "A minimal design that speaks for itself",
        fontSize: 26,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 1.4,
      },
    ],
  },
];
